language: java
install: true

jdk:
- oraclejdk8

services:
- docker

before_install:
- echo $PRIVATE_REG_PASSWORD | docker login -u "$PRIVATE_REG_USERNAME" --password-stdin $PRIVATE_REG_HOST

script:
- ./gradlew build --scan -s -x test
- ./gradlew dockerBuildImage
- ./gradlew dockerPushImage

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/