server:
  port: 8083

logging:
  level:
    org.springframework.security: debug

client:
  clients:
  - id: userapp
    grantTypes: password
    secret: "{pbkdf2}30d47c8ef17066e65750bb6469b951dbaf8b40d4cf4b421490ffff92da00804700c8b8fb92cc9ce0"
    scopes: user:read
    accessTokenValiditySeconds: 3600
  - id: messageapp
    grantTypes: client_credentials
    secret: "{pbkdf2}30d47c8ef17066e65750bb6469b951dbaf8b40d4cf4b421490ffff92da00804700c8b8fb92cc9ce0"
    scopes: message:read
    accessTokenValiditySeconds: 3600
