server:
  port: 8080

logging:
  level:
    org.springframework.security: debug
    org.springframework.cloud.gateway: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/oauth/token

message-url: http://localhost:8081
user-url: http://localhost:8082
auth-url: http://localhost:8083
