server:
  port: 8084
  servlet:
    session:
      cookie:
        name: SSOSESSION
security:
  oauth2:
    client:
      client-id: cartapp
      client-secret: 123456
      access-token-uri: http://localhost:8083/oauth/token
      user-authorization-uri: http://localhost:8083/oauth/authorize
      registered-redirect-uri: http://localhost:8084/login
      authorized-grant-types: authorization_code
    resource:
      user-info-uri: http://localhost:8083/about/me

spring:
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: debug