server:
  port: 8086
  servlet:
    session:
      timeout: 5m
      cookie:
        name: AUTHMORE_SESSION
  tomcat:
    max-threads: 5

spring:
  data:
    mongodb:
      database: authmore

token:
  policy: REDIS