server:
  port: 8091

authmore:
  resource:
    resource-id: MAILBOX
    token-info-url: http://localhost:8086/oauth/check_token
    jwk-set-url: http://localhost:8086/oauth/jwks
    client-id: 5cb88433ee173c60c379e04f
    client-secret: 6LJTlUAfSo4TZhgRdAh2BC1hfUGROEpT
