server:
  port: 8090

authmore:
  client:
    client-id: 5cb7e7bcee173c60c379e04e
    client-secret: afLTqlcRUr32UC3nWiUNIMsfOmVlzuzX
    token-issue-url: http://localhost:8086/oauth/token
    redirect-uri: http://localhost:8090/signin
    authorize-url: http://localhost:8086/authorize