server:
  port: 8090

authmore:
  client:
    client-id: 5cb7e7bcee173c60c379e04e
    client-secret: afLTqlcRUr32UC3nWiUNIMsfOmVlzuzX
    request-token-on-startup: true
    scope: PROFILE+EMAIL
    token-issue-url: http://platform.authmore/oauth/token
    # "/implicit.html" for implicit mode
    redirect-uri: http://client.authmore/inbox
    authorize-uri: http://platform.authmore/authorize
    # only for implicit mode
    implicit-token-uri: http://client.authmore/token
    implicit-redirect-uri: http://client.authmore/implicit.html